name: Auto Scan

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: # Thêm nút bấm chạy thủ công trên GitHub

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Sửa lại dòng này để ép xóa sạch bộ nhớ đệm cũ và chỉ cài thư viện tính toán lõi ổn định
      - run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pandas requests numpy

      - run: python main.py
